//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryInventoryProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_IngredientDetails
    {
        public int IngredientId { get; set; }
        public string IngredientName { get; set; }
        public string RecipeName { get; set; }
        public string RecipeType { get; set; }
        public string Measurement { get; set; }
        public string IngredientTypeName { get; set; }
        public string BrandName { get; set; }
        public string SellingWeight { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public int RecipeId { get; set; }
    }
}
