//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryInventoryProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RecipeDetails
    {
        public int RecipeId { get; set; }
        public string RecipeName { get; set; }
        public string RecipeTypeName { get; set; }
        public Nullable<int> Yield { get; set; }
        public int RecipeTypeId { get; set; }
    }
}
